# This is a simple test system for the dissociation of sodium chloride in
# tip3p water. It was converted from the gromacs files using InterMol. Note
# that the B states is already at 4.0 angstrom to cut down path lengths for
# testing purposes. Also, we do not use PME here.

[dask]
workers = 4
wmdrun = ['0', '0', '0', '0'] # not used
[simulation]
interfaces = [2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 4.0]
steps = 100
seed = 0
load_dir = 'load'
#shooting_moves = ['sh','sh','wf','wf','wf','wf','wf'] # shooting and wire-fencing
shooting_moves = ['sh','sh','sh','sh','sh','sh','sh'] # only shooting

[simulation.tis_set]
maxlength = 10000
allowmaxlength = false
zero_momentum = true
n_jumps = 2 # not used when all moves are 'sh'
interface_cap = 3.6 # not used when all moves are 'sh'

[engine]
class = 'lammps'
engine = 'lammps'
input_path = 'lammps_input'
lmp = 'lmp_stable' # or 'mpirun -np 2 lmp_exe'
timestep = 2.0 # fs
subcycles = 5
temperature = 300

[orderparameter]
class = 'Distance'
index = [0, 1]
periodic = true

[output]
data_dir = "./" # where to store infretis_data.txt
screen = 1 # how often to print to sim.log
pattern = false # how often we print info of which worker is in which ensemble at any time to pattern.txt
delete_old = true # delete old accepted trajectories (e.g. .trr or .xyz files)
