[dask]
workers = 40
files=["orderp.py"]
wmdrun = [
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
    'srun -n 1 -N 1 -c 12 -G 0 --exclusive --mem 10G /users/zdaniel/software/cp2k/cp2k-2023.1-Linux-gnu-x86_64.ssmp',
]

[simulation]
pyretis_inp = "retis.rst"
internal = false
states_ab = [
    0.27,
    0.45,
]
steps = 1000000
seed = 0
save_loc = "./"
load_dir = "trajs"
bm_steps = 100
bm_intfs = [
    -900.0,
     900.0,
]

[output]
backup = "backup"
store_paths = true
screen = 1
pattern = true
data_dir = "./"
delete_old = true
