# water dissociation

[dask]
workers = 1
files=["orderp.py"]
wmdrun = [
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
    'cp2k', 'cp2k', 'cp2k',
]

[simulation]
interfaces = [ 1.0700, 1.0757, 1.0870, 1.0951, 1.1030,
               1.1104, 1.1181, 1.1253, 1.1327, 1.1399,
               1.1469, 1.1541, 1.1613, 1.1685, 1.1757,
               1.1831, 1.1903, 1.1977, 1.2054, 1.2130,
               1.2209, 1.2288, 1.2369, 1.2455, 1.2541,
               1.2631, 1.2724, 1.2822, 1.2922, 1.3031,
               1.3142, 1.3263, 1.3393, 1.3534, 1.3690,
               1.3866, 1.4070, 1.8000, 2.0000, 2.5000,
               20.0000]
steps = 1000000
seed = 0
load_dir = "load"
shooting_moves = ['sh', 'sh', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf', 'wf', 'wf', 'wf', 'wf',
                  'wf']

[simulation.tis_set]
maxlength = 250000
allowmaxlength = false
zero_momentum = false
temperature = 300
high_accept = true
n_jumps = 2
interface_cap = 3.00

[engine]
class = 'cp2k'
engine = 'cp2k'
timestep = 0.5
cp2k_format = 'xyz'
input_path = 'cp2k_data'
# cp2k = "srun --exact -N 1 -n 12 -c 1 --mem-per-cpu=4G cp2k.psmp"
cp2k = "cp2k.psmpp"
subcycles = 1
extra_files = ['BASIS_MOLOPT', 'GTH_POTENTIALS']
temperature = 300

[orderparameter]
class = 'OrderX'
module = 'orderp.py'
index = [0, 1]
periodic = true

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = false
