[dask]
workers = 8
files = ["orderp.py"]

wmdrun = [
        'gmx mdrun -pin on -pinoffset 0 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 4 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 8 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 12 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 16 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 20 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 24 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',
        'gmx mdrun -pin on -pinoffset 28 -pinstride 1 -ntomp 4  -ntmpi 1 -notunepme -nb gpu -bonded cpu -pme gpu',]


[simulation]
# optimized interfaces, which are different from the article
interfaces = [ -0.85, -0.839118912, -0.82730273, -0.814381438, -0.800015002, -0.784033403, -0.765926593, -0.745269527, -0.721212121, -0.692989299, -0.65949595, -0.619371937, -0.571682168, -0.515066507, -0.447059706, -0.36009601, -0.228162816, 1.5]
steps = 100000
seed = 0
load_dir = 'load'
shooting_moves = ['sh', 'sh', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf']

[simulation.tis_set]
maxlength = 160000
allowmaxlength = false
zero_momentum = true # momentum true
temperature = 340
high_accept = true
n_jumps = 3
interface_cap = 0.0

[engine]
class = 'gromacs'
engine = 'gmx'
timestep = 0.002
gmx_format = 'g96'
input_path = 'gromacs_input'
gmx = 'gmx'
subcycles = 250

[orderparameter]
class = 'NeuralNetDiffmap'
module = 'orderp.py'

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = true 
