# infretis config

[dask]
workers = 1 # until 9 or 10 here, you can have even more but then you need to increase interfaces = [...] list
wmdrun = [
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 0 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 1 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 2 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 3 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 4 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 5 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 6 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 7 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 8 -pin on",
	"gmx mdrun -ntomp 1 -ntmpi 1 -pinoffset 9 -pin on",
]

[simulation]
# can add even more workers, but have to add more interfaces between e.g. 0.36 and 0.38 (not over 0.7)
# in an increasing order and then again copy the load/1/ path-folder to e.g. load/11/ if you add 1 more interface
# and load/11/, load/12/ if you add 2 more interfaces
interfaces = [0.32, 0.34, 0.36, 0.3601, 0.3602, 0.3603, 0.3604, 0.3605, 0.38, 0.41, 0.70]
steps = 1000
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf','wf']


[simulation.tis_set]
maxlength = 50000
allowmaxlength = false
zero_momentum = true # momentum true
n_jumps = 2
temperature = 300


[engine]
class = 'gromacs'
engine = 'gmx'
timestep = 0.002
gmx_format = 'g96'
input_path = 'gromacs_input'
gmx = 'gmx' # gromacs executable
subcycles = 5
temperature = 300

[orderparameter]
class = 'Distance'
index = [ 0, 1]
periodic = true

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = false
